export const FETCH_ID_LIST = 'FETCH_ID_LIST';
export const FETCH_DATA_SOURCE = 'FETCH_DATA_SOURCE';
export const GET_APPLICATION_DATA_FIELDS = 'GET_APPLICATION_DATA_FIELDS';
export const GET_BUILDNAME_LIST = 'GET_BUILDNAME_LIST';
export const SET_BUILDNAME_FILTER = 'SET_BUILDNAME_FILTER';
export const GET_BUILDVER_LIST = 'GET_BUILDVER_LIST';
export const SET_BUILDVER_FILTER = 'SET_BUILDVER_FILTER';